# Generated by Django 4.2.11 on 2024-06-10 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Кобель'), ('F', 'Сука'), ('N/A', 'Не определен')], default='N/A', max_length=20, verbose_name='Пол собаки')),
                ('name', models.CharField(default='Нет данных', max_length=20, verbose_name='Кличка собаки ')),
                ('date_of_birth', models.DateField(default=datetime.datetime.now, verbose_name='Дата рождения')),
                ('personality', models.CharField(choices=[('A', 'агрессивный'), ('S', 'охранник'), ('N', 'спокойный'), ('G', 'добродушный'), ('C', 'милашка'), ('T', 'пугливый')], default='N', max_length=20, verbose_name='Характер собаки')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Окрас собаки')),
                ('image', models.ImageField(blank=True, upload_to='dog_images/', verbose_name='Иллюстрации')),
                ('features', models.TextField(default='Без особенностей', verbose_name='Особенности собаки')),
                ('datecreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карточки')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров питомца')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
        migrations.CreateModel(
            name='Poroda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poroda', models.CharField(default='Беспопородная', max_length=100)),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datа_creation', models.DateField(default=datetime.datetime(2024, 6, 10, 22, 8, 22, 615694), verbose_name='Дата создания новости')),
                ('title', models.CharField(max_length=200, verbose_name='Название новости')),
                ('content', models.TextField(verbose_name='Содержание новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название иллюстрации')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='Иллюстрации к новости')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.post', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Иллюстрация',
                'verbose_name_plural': 'Иллюстрации',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='Вес собаки')),
                ('sterilization', models.CharField(choices=[('Y', 'Стерлизован(а)'), ('N', 'Нет'), ('N/Y', 'Нет данных')], default='N/Y', max_length=20, verbose_name='Статус стерилизации')),
                ('date_vaccination', models.DateField(default=datetime.datetime(2023, 6, 5, 22, 8, 22, 614662), verbose_name='Дата прививки')),
                ('date_worms', models.DateField(default=datetime.datetime(2023, 6, 5, 22, 8, 22, 614662), verbose_name='Дата приема глистогонного')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animals.dog', verbose_name='Данные животного')),
            ],
            options={
                'verbose_name': 'Состояние животного',
                'verbose_name_plural': 'Состояние животного',
            },
        ),
        migrations.CreateModel(
            name='DogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carusel_images/', verbose_name='Иллюстрации к карусели')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.dog')),
            ],
            options={
                'verbose_name': 'Иллюстрация к карусели',
                'verbose_name_plural': 'Иллюстрации к карусели',
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='fenotip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.poroda', verbose_name='Порода собаки'),
        ),
        migrations.CreateModel(
            name='Disease_Vid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.CharField(choices=[('H', 'Здорова(а)'), ('S', 'Болен(а)'), ('D', 'Умерла')], default='H', max_length=20, verbose_name='Состояние собаки')),
                ('description', models.TextField(blank=True, default='Без патологий', verbose_name='Диагноз')),
                ('datecreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи ')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse', to='animals.health', verbose_name='Болезнь собаки')),
            ],
            options={
                'verbose_name': 'Заболевание',
                'verbose_name_plural': 'Заболевания',
            },
        ),
        migrations.CreateModel(
            name='Adress_Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(default='Нет информации', max_length=100, verbose_name='Город ')),
                ('steet', models.CharField(blank=True, max_length=100, verbose_name='Улица ')),
                ('home', models.IntegerField(blank=True, null=True, verbose_name='Номер дома владельца')),
                ('apartment', models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры владельца')),
                ('surname', models.CharField(blank=True, default='Приют', max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_location', models.DateField(default=datetime.datetime(2024, 6, 10, 22, 8, 22, 614662), verbose_name='Дата передачи владельцу')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.dog', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Адрес нахождения животного',
                'verbose_name_plural': 'Адреса нахождения животного',
            },
        ),
        migrations.CreateModel(
            name='Adress_Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(default='Ханты-Мансийск', max_length=100, verbose_name='Город обнаружения')),
                ('steet', models.CharField(blank=True, max_length=100, verbose_name='Улица ')),
                ('home', models.IntegerField(blank=True, null=True, verbose_name='Номер дома ')),
                ('notes', models.CharField(default='Нет дополнительной информации о месте обнаружения', max_length=300, verbose_name='Дополнительная информация')),
                ('datefind', models.DateTimeField(default=datetime.datetime(2024, 6, 10, 22, 8, 22, 613647), verbose_name='Дата обнаружения')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.dog', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Адрес обнаружения животного',
                'verbose_name_plural': 'Адреса обнаружения животного',
            },
        ),
    ]
