# Generated by Django 4.2.11 on 2024-06-10 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress_find',
            name='datefind',
        ),
        migrations.AddField(
            model_name='adress_find',
            name='date_find',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 22, 37, 32, 893720), verbose_name='Дата обнаружения'),
        ),
        migrations.AlterField(
            model_name='adress_owner',
            name='date_location',
            field=models.DateField(default=datetime.datetime(2024, 6, 10, 22, 37, 32, 893720), verbose_name='Дата передачи владельцу'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_vaccination',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 22, 37, 32, 893720), verbose_name='Дата прививки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_worms',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 22, 37, 32, 893720), verbose_name='Дата приема глистогонного'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datа_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 10, 22, 37, 32, 894757), verbose_name='Дата создания новости'),
        ),
    ]
