# Generated by Django 4.2.11 on 2024-06-11 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_adress_find_date_find_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress_find',
            name='date_find',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 10, 47, 18, 458837), verbose_name='Дата обнаружения'),
        ),
        migrations.AlterField(
            model_name='adress_find',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_adfnd', to='animals.dog', verbose_name='Животное'),
        ),
        migrations.AlterField(
            model_name='adress_owner',
            name='date_location',
            field=models.DateField(default=datetime.datetime(2024, 6, 11, 10, 47, 18, 458837), verbose_name='Дата передачи владельцу'),
        ),
        migrations.AlterField(
            model_name='adress_owner',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_adrow', to='animals.dog', verbose_name='Животное'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_vaccination',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 10, 47, 18, 460010), verbose_name='Дата прививки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_worms',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 10, 47, 18, 460010), verbose_name='Дата приема глистогонного'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datа_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 11, 10, 47, 18, 460010), verbose_name='Дата создания новости'),
        ),
    ]
