# Generated by Django 4.2.11 on 2024-06-13 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_adress_find_date_find_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress_find',
            old_name='steet',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='adress_owner',
            old_name='steet',
            new_name='street',
        ),
        migrations.AlterField(
            model_name='adress_find',
            name='date_find',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 14, 15, 58, 23443), verbose_name='Дата обнаружения'),
        ),
        migrations.AlterField(
            model_name='adress_owner',
            name='date_location',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 14, 15, 58, 23443), verbose_name='Дата передачи владельцу'),
        ),
        migrations.AlterField(
            model_name='disease_vid',
            name='health',
            field=models.CharField(choices=[('H', 'Здорова(а)'), ('S', 'Болен(а)'), ('D', 'Умер(ла)')], default='H', max_length=20, verbose_name='Состояние собаки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_vaccination',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 14, 15, 58, 23443), verbose_name='Дата прививки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_worms',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 14, 15, 58, 23443), verbose_name='Дата приема глистогонного'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datа_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 14, 15, 58, 24553), verbose_name='Дата создания новости'),
        ),
    ]
