# Generated by Django 4.2.11 on 2024-06-25 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_rename_steet_adress_find_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress_find',
            name='date_find',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 23, 11, 25, 930048), verbose_name='Дата обнаружения'),
        ),
        migrations.AlterField(
            model_name='adress_owner',
            name='date_location',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 23, 11, 25, 931057), verbose_name='Дата передачи владельцу'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(blank=True, max_length=150, verbose_name='Окрас собаки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_vaccination',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 23, 11, 25, 931057), verbose_name='Дата прививки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_worms',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 23, 11, 25, 931057), verbose_name='Дата приема глистогонного'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datа_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 25, 23, 11, 25, 931057), verbose_name='Дата создания новости'),
        ),
    ]
