# Generated by Django 4.2.11 on 2024-07-12 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_adress_find_date_find_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress_find',
            name='date_find',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 14, 37, 21, 93737), verbose_name='Дата обнаружения'),
        ),
        migrations.AlterField(
            model_name='adress_owner',
            name='date_location',
            field=models.DateField(default=datetime.datetime(2024, 7, 12, 14, 37, 21, 94820), verbose_name='Дата передачи владельцу'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(upload_to='dog_images/', verbose_name='Фотография животного'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_vaccination',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 14, 37, 21, 94820), verbose_name='Дата прививки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_worms',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 14, 37, 21, 94820), verbose_name='Дата приема глистогонного'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datа_creation',
            field=models.DateField(default=datetime.datetime(2024, 7, 12, 14, 37, 21, 95910), verbose_name='Дата создания новости'),
        ),
    ]
