# Generated by Django 4.2.11 on 2024-07-16 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_message_alter_adress_find_date_find_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress_find',
            name='date_find',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 9, 37, 32, 214128), verbose_name='Дата обнаружения'),
        ),
        migrations.AlterField(
            model_name='adress_owner',
            name='date_location',
            field=models.DateField(default=datetime.datetime(2024, 7, 16, 9, 37, 32, 214286), verbose_name='Дата передачи владельцу'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_vaccination',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 9, 37, 32, 214286), verbose_name='Дата прививки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_worms',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 9, 37, 32, 214286), verbose_name='Дата приема глистогонного'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datа_creation',
            field=models.DateField(default=datetime.datetime(2024, 7, 16, 9, 37, 32, 215438), verbose_name='Дата создания новости'),
        ),
    ]
