# Generated by Django 4.2.11 on 2024-07-18 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_alter_adress_find_date_find_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='datа_creation',
        ),
        migrations.AddField(
            model_name='post',
            name='datecreation',
            field=models.DateField(default=datetime.datetime(2024, 7, 18, 15, 36, 18, 47123), verbose_name='Дата создания новости'),
        ),
        migrations.AlterField(
            model_name='adress_find',
            name='date_find',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 15, 36, 18, 45064), verbose_name='Дата обнаружения'),
        ),
        migrations.AlterField(
            model_name='adress_owner',
            name='date_location',
            field=models.DateField(default=datetime.datetime(2024, 7, 18, 15, 36, 18, 46124), verbose_name='Дата передачи владельцу'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_vaccination',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 15, 36, 18, 46124), verbose_name='Дата прививки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_worms',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 15, 36, 18, 46124), verbose_name='Дата приема глистогонного'),
        ),
    ]
