# Generated by Django 4.2.11 on 2024-07-18 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0015_alter_message_options_remove_post_datа_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress_find',
            name='date_find',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 15, 38, 51, 318737), verbose_name='Дата обнаружения'),
        ),
        migrations.AlterField(
            model_name='adress_owner',
            name='date_location',
            field=models.DateField(default=datetime.datetime(2024, 7, 18, 15, 38, 51, 318737), verbose_name='Дата передачи владельцу'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_vaccination',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 15, 38, 51, 319814), verbose_name='Дата прививки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_worms',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 15, 38, 51, 319814), verbose_name='Дата приема глистогонного'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datecreation',
            field=models.DateField(default=datetime.datetime(2024, 7, 18, 15, 38, 51, 319814), verbose_name='Дата создания новости'),
        ),
    ]
